version: "1"
rules:
  - base: main
    upstream: KelvinTegelaar:main
    mergeMethod: merge
  - base: dev
    upstream: KelvinTegelaar:dev
    mergeMethod: none
  - base: docs
    upstream: KelvinTegelaar:docs
    mergeMethod: none
  - base: jit-admin
    upstream: KelvinTegelaar:jit-admin
    mergeMethod: none
  - base: docs-maintenance
    upstream: KelvinTegelaar:docs-maintenance
    mergeMethod: none
  - base: KelvinTegelaar-patch-2
    upstream: KelvinTegelaar:KelvinTegelaar-patch-2
    mergeMethod: none
  - base: KelvinTegelaar-patch-1
    upstream: KelvinTegelaar:KelvinTegelaar-patch-1
    mergeMethod: none
